export const NAMES: string[] = [
  'Amigo',
  'Assistant to the President & Deputy National Security Advisor',
  'Barry Bluejeans',
  'BATMAN',
  'Befroe',
  'Best Friend',
  'Boss',
  'Breb',
  'Bro/Brah',
  'Bud',
  'Buddy',
  'Captain',
  'Cheif',
  'Cpt. Captain Bane',
  'Comrade',
  'Cool Cat',
  'Daniel DeVito',
  'Doc',
  'Dude',
  'Fam',
  'fellow human',
  'Friend',
  'Frodo',
  'G',
  'Garfield, Enemy of all Mondays',
  'Guy/Gal/Gull',
  'Habibi',
  '(Insert Name)',
  'Legolas',
  'Liz Lemon',
  'Love',
  'Ma\'m/Man/Mallcop',
  'Mate',
  'Mr/Ms President',
  'Pal',
  'Partner',
  'Poe, the Kung-Fu Panda',
  'Partner',
  'Queen',
  'Radbot (an actual real historical name)',
  'Sailor',
  'Sarge',
  'Scooby Doo',
  'Scrappy Doo',
  'Sheldon Cooper (from The Big Bang)',
  'Sir/Madam/Nobleperson',
  'Skipper',
  'Weary Traveller',
  'Xenia',
  'Your Eminence',
  'Your Highness',
  'Your Holiness',
  'Your Honor',
  'Your Majesty'
];
