export const RHYMES: string[] = [
'I love fruity pebbles|major|',
'please enjoy my website|major|',
'you deserve to live life|major|',
'I\'ll be your friend|major|',
'Bananas have to ripen in a certain way',
'computers rule|major|',
'you\'re tubular|major|',
'I love to rhyme|major|',
'Rappa rappa rappa, a tappa huppa huppa',
'let\'s have some fun|major|',
'I\'m afraid of snakes|major|',
'support local business|major|',
'I love to program|major|',
'I accept you|major|',
'war is coming|major|',
'support women of color|major|',
'I\'m the plowingest guy in the U.S.A',
'be honest with yourself|major|',
'I\'ve lost my mind|major|',
'I respect my elders|major|',
'please get me a job|major|'
];
